# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pfeditor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_87e703631b2a4098bed652da94cf24ae }}
        password: ${{ secrets.AzureAppService_ContainerPassword_23df7f9d3bca457e8c2fd3ae1423d5b9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_87e703631b2a4098bed652da94cf24ae }}/pfeditor:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pfeditor'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_103f6428184f487ba7d731fb493822fa }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_87e703631b2a4098bed652da94cf24ae }}/pfeditor:${{ github.sha }}'